### PR TITLE
Mc tasks read

### PR DESCRIPTION
**Pull request by michaelclark2**
to test: 
log in as nutshell@nutshell.com

### CODE REVIEW

**Comment by amillion3** [comment]
I'm not seeing any tasks print on my end. No error messages either...
screen shot 2018-06-14 at 10 43 36 pm

**Comment by michaelclark2** [comment]
try logging in as nutshell@nutshell.com, its only displaying the current users tasks and the only users with data are the ones we seeded

**Comment by amillion3** [comment]
Ah, there we go. Thought it might be something like that.

👍

**Comment by johnachor** [comment]
Looks good.  You can resolve that merge conflict by just removing the line that calls friends.initializeFriends(); because I renamed that function.

**Pull request merged**
